version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  filesaver:
    image: iqtlabs/edgetech-filesaver:latest
    network_mode: "host"
    build:
      context: ../edgetech-filesaver/filesaver
      dockerfile: ./Dockerfile
    environment:
      - TO_SAVE_TOPIC=/AISonobuoy/<HOSTNAME>/AIS/edgetech-daisy/bytestring
      - C2_TOPIC=/AISonobuoy/<HOSTNAME>/C2/edgetech-c2/string
      - DATA_ROOT=/sensor-data
      - SENSOR_DIR=ais
      - FILE_PREFIX=daisy_ais_
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
